config/routes.rb
RailsMastercoin::Application.routes.draw do
  get "charts/weekly"
  get "charts/yearly"
  get "charts/monthly"
  get "charts/MSC_BTC"
  resources :homes

  resources :transactions
  resources :searches

  namespace "mastercoin_verify", defaults: {format: 'json'} do
    resources :addresses
    resources :transactions
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :addresses do
        member do
          get :unspent
        end
      end

      resources :selling_offers do 
        collection do
          get :current
        end
      end
      resources :purchase_offers

      resources :transactions do
        collection do
          get :exodus
          get :simple_send
          get :invalid
        end
      end
    end
  end

  namespace :raw do
    resources :transactions
  end

  resources :advisors do 
    collection do 
      post :sell
    end
  end

  resources :selling_offers
  resources :simple_sends
  resources :purchase_offers
  resources :order_books
  resources :advisors
  resources :addresses

  get "help" => "homes#help"

  get "api_docs" => "homes#api_docs"

  root to: "homes#index"

  

end

app/controllers/order_books_controller.rb
class OrderBooksController < ApplicationController
  def index
    @offers = []
    SellingOffer.select("distinct(address)").collect(&:address).each do |address|
      offer = SellingOffer.where(address: address).valid.current
      @offers << offer if offer.present?
    end
  end
end

app/views/order_books/index.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading 
        Distributed order book
      .panel-body
        %p Here you will see the broadcasted distributed Mastercoin orders for sale using the Mastercoin protocol itself.
      %table.table.table-condensed
        -if @offers.find_all{|x| x.amount_available > 0}.any?
          %tr
            %th
            %th Seller
            %th Unit price
            %th Units available
            %th Bitcoin desired
            %th Time limit
            %th Fee required
            %th Currency
            %th Actions
          -@offers.each do |offer|
            -next if offer.amount_available <= 0
            %tr
              %td=link_to image_tag('details.png'), transaction_path(offer.tx_id), :"data-toggle" => :tooltip, title: offer.tx_id, class: "transaction-tooltip", :"data-placement" => "right"
              %td=link_to offer.address, address_path(offer.address)
              %td=number_to_currency(offer.price_per_coin, unit: "฿")
              %td
                =number_to_currency(offer.amount_available)
              %td=number_to_currency(offer.amount_desired, unit: "฿")
              %td=offer.time_limit
              %td=offer.required_fee
              %td=offer.currency
              %td=link_to "Buy", new_purchase_offer_path(amount: offer.amount_available, address: offer.address, currency_id: offer.currency_id, forced_fee: offer.required_fee)
        -else
          %tr
            %td{colspan: 8} No open orders
.row
  .col-md-6
    .panel.panel-default
      .panel-heading 
        MSC/BTC Chart
      #graph-container

  .col-md-6
    .panel.panel-default
      .panel-heading 
        Accepted distributed exchange transactions
      .panel-body
        %p Here is a list of recent bought transactions that were bought via the distributed system.
      %table.table
        %tr
          %th Transaction
          %th Unit price
          %th Amount
          %th Currency
        -PurchaseOffer.valid.accepted.limit(8).each do |offer|
          %tr
            %td=link_to truncate(offer.tx_id), transaction_path(offer.tx_id)
            %td=number_to_currency(offer.selling_offer.price_per_coin, unit: "฿")
            %td=offer.amount
            %td=offer.currency
:javascript
  $(function() {
    // Create the chart
    $('#graph-container').highcharts('StockChart', {
        chart: {
            renderTo: 'container'
        },

        rangeSelector: {
            selected: 1
        },

        title: {
            text: 'MSC/BTC price chart'
        },
        
        series: [{
            name: 'MSC/BTC',
            data: #{raw PurchaseOffer.collect_data.to_json},
            type: 'spline',
            tooltip: {
              valueDecimals: 2
            }
        }]
    });
  });
=content_for(:title) do
  Mastercoin distributed exchange order book